### ISSUE TITLE
Issues in edit doctype & customize form

### ISSUE THREAD

**Issue by chechani** [kid1194/frappe-better-select-control#1]
Hi, 

After installing this app, when we go to edit doctype and try to edit properties of a field, there is an error in console log and we are not allowed to open that field properties.

Also In Customize form we got the same error and no fields were loaded in customize form

we are frappe v14.22 and erpnext 14.12.1

**Comment by kid1194** [comment]
@chechani Thank you for reporting this..

Can you please share the error that appeared?
A screenshot of the console log would be better..

**Comment by chechani** [comment]
![Screenshot 2023-01-20 at 15 04 12](https://user-images.githubusercontent.com/6291292/213662921-ccd5a062-484b-4bc4-a7e4-68c8da608f6c.png)

**Comment by kid1194** [comment]
@chechani Thanks a lot buddy for posting a screenshot. It helped a lot..

I have fixed the bug and updated the plugin so please do update and check if there is any other bugs..

Best regards..
